name: Upload Movie App
on:
    push:
      branches:
        - main
        - develop
    pull_request:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code sur le repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./
        build: npm run build
        start: npm run start
        wait-on: 'http://localhost:3000'
        browser: chrome

      # Configure la clé SSH pour se connecter à ton VPS
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
